#!/bin/bash

# Script de suppression d'adress mail dans la db
# Couleur pour une compréhension B=bleu/N=classique/M=mauve/R=rouge/Y=jaune
R="\033[0;31m"
B="\033[0;34m"
Y="\033[0;33m"
M="\033[0;95m"
N="\033[0m"

# SQL affiche les id et emails contenu dans la database
output=$(mysql -u root -t <<MY_QUERY
USE maildb
SELECT id, email AS "Adresse Mail" FROM virtual_users
ORDER BY id
MY_QUERY
)
printf "$Y$output$N\n"

# SQL stocke les ID dans un fichier id.txt
id=$(mysql -u root -N <<MY_QUERY
USE maildb
SELECT id FROM virtual_users
ORDER BY id
MY_QUERY
)
echo "$id" > id.txt

# choix de l'adresse à supprimer
echo "Email a supprimer (Choisir un numéro différent de 0) ?"
read a

## Verifie si id est bien dans la liste (id.txt)
if grep -q $a id.txt; then

  printf "Email a supprimer : $R\n"
  mysql -u root -N <<MY_QUERY
  USE maildb
  SELECT email FROM virtual_users WHERE id='$a'
MY_QUERY
printf "$N"
mysql -u root <<MY_QUERY
  USE maildb
  DELETE FROM virtual_users WHERE id='$a'
MY_QUERY


# affiche la liste après l'execution de la commande pour s'assurer de la supression puis supprime id.txt
show=$(mysql -u root -t <<MY_QUERY
USE maildb
SELECT id, email AS "Adresse Mail" FROM virtual_users
ORDER BY id
MY_QUERY
)
printf "$M$show$N\n"
$(rm id.txt)
exit 1
fi
echo "id not in, try again"
$(rm id.txt)