#!/bin/bash

# Affiche les ID et les mails présent dans la DB

# Colors - code (Red-Blue-Orange-Magenta-None)
O="\033[0;33m"
N="\033[0m"

# SQL affiche les id et emails de la db
output=$(mysql -u root -t <<MY_QUERY
USE maildb
SELECT id, email AS "Adresse Mail" FROM virtual_users
ORDER BY id
MY_QUERY
)
printf "$O$output$N\n"