#!/bin/bash

# Affiche une liste des id et les mails présent dans la database

#Couleur R=rouge / B=bleu / Y=jaune / M=mauve / N=classique 
R="\033[0;31m"
B="\033[0;34m"
Y="\033[0;33m"
M="\033[0;95m"
N="\033[0m"

# SQL affiche les id et emails de la db
output=$(mysql -u root -t <<MY_QUERY
USE maildb
SELECT id, email AS "Adresse Mail" FROM virtual_users
ORDER BY id
MY_QUERY
)
printf "$Y$output$N\n"