FROM ubuntu:latest


RUN apt-get update -y
RUN apt-get install -y lynx
RUN apt-get install -y mutt
RUN apt-get install -y dnsutils
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y nano


CMD tail -f /dev/null




